version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/code/data
      - ./hf_cache:/root/.cache/huggingface  # <--- to save downloaded model
    env_file:
      - .env